Squashing commits from minimal_rdmol
Squashing commits from minimal_rdmol

Fixed isAtomListQuery broken in rebase

Build fix

Build fix in _isAtomListQuery

string_view fixes in GraphMol

GCC and Clang build fixes in catch_romol_compat.cpp

More build fixes

A couple test fixes

Made changes to Property and PropIterator to implement missing behaviour in MaeWriter.cpp, to try to fix build break

Build fixes

Removed a raiseNonImplementedFunction in Wrap/MolOps.cpp, which will hopefully fix the GCC build break

GCC build fix

Fixed bug with atom and bond membership data in RingInfoCache

Fixed logic in queryIsAtomBridgeheadInternal

Check ownership precondition earlier in addAtom and addBond for test cases

Boolean OR for bools, not bitwise OR

Added special handling for some special case properties

Added support for _MolFileBondEndPts prop in RDMol::removeAtom, and updated SubstanceGroup owning mols upon move assignment

Updated a few conditions in catch_graphmol.cpp for expected behaviour changes

Ported findSSSR and symmetrizeSSSR to use new interface and use fewer memory allocations via flat arrays and avoiding redundant copies, to better match how ring info is stored in the new RingInfoCache data structure.

Build fix

Fixed handling of multiple fragments in findSSSR

Fixed several bugs in symmetrizeSSSR and findSSSR

Fixed bug in findSSSR

Fixed subtle compatibility synchronization bug in findSSSR

To fix code that inspects child queries of a Query object, give a way to unwrap CompatQuery and NonCompatQuery wrappers

GCC and Clang don't like "typename" here after all

Fixed bug with stereo group synchronization when calling non-const RDMol::getStereoGroups, e.g. in Chirality::cleanupStereoGroups

Started writing RDMol porting guide

Added extraRings property in findSSSR, just in case some calling code checks for it

Fixed 'DEBUG=1' build

Bugfix: Chemdraw test.cpp:"Fragments" failing test is now fixed.

There was an iterator invalidation causes addBond to be called on the same atom
and bonds twice. By copying the iterator to a vector, the problem is now fixed.

Also added additional tests to the fragment test to ensure cleanup is done
correctly.

Build vector using iterator begin() & end()

Move the xbonds vector and re-use its memory when possible.

Wrote more of RDMol porting guide

Wrote some more of RDMol porting guide

Wrote more of RDMol porting guide

Bugfix: Unpickled ring data wrong when done consecutively

When unpickling into an existing molecule with an atom with additional ring
data, the previous ringinfo data would get reset when adding the bonds. We now
save the ringinfo, add the bonds, and restore the ringinfo.

Remove commented cerr outputs

Recompute RingInfo instead of saving previous RingInfo

When unpickling into an existing molecule, it happens that when you add bonds it
destroys the previous ringinfo. Instead of trying to save it when this happens,
we re-compute the ringinfo after adding the bonds.

Set owning molecule before setting bond bookmark

Switch back to restoring ringinfo

Fixes segfault in testPickler

In the line:
existing = addPerElementProp(name, scope, T(), computed, false);
when T = ExplicitBitVect, the default contstructor left dp_bits=nullptr. Later
in the addPerElementProp routine a copy constructor was called, which assumed a
non-null dp_bits pointer. By making the dp_bits non-null, we avoid the segfault.

Added pickle/unpickle support for properties

All tests in `graphmoltestPickler` now pass.

Property pickle support uses new property iterator

(mostly) Match behavior in PR#8934

We removed the ringInfo reset after the addBonds when pickling. The reference
resets the also resets the property cache, but we don't do this.

Fixed error around ignoring bond properties when pickling

Handle pickle/unpickle of explicit properties

Fixed a problem writing pickle data where string query data wasn't correctly handled

The pickle writer was outputting a "RDVal" instead of a string, and there wasn't
any method to serialize the RDVal. By correctly getting the string, it was able
to be serialized properly, fixing the pickle, which fixed the unpickling, which
threw an error.

We also added a check for pickleFlags, but this wasn't necessary for the
catch_pickle tests, but maybe elsewhere it will be relevant.

Cached compat ringInfo pointer causing trouble in catch_adjustquery.

Re-getting ringInfo after ringInfo was generated internally, solved a problem
where the compat interface was stale.

We added an extra function that was thought to help, but actually didn't help.
It seems useful anyway, so keeping it.

Current thinking: don't satisfy old proplist requirement

Old proplist always had computedPropName as a prop. This meant that it always
was counted and existed. This is difficult to support using new backend and we
are dropping this, unless someone desperately wants it.

Fixes bug in catch_canon.cpp. Properties weren't being copied correctly

Properties with unsigned int and int were converted to ANY type, so we added
some extra conversion tooling to help ensure that we don't end up in ANY type
for int - unsigned int. That said, we also added a fix for any time just in case.

Fixed a regression in romolcompatTestsCatch

Don't try to convert float32 -> int32 in property storage

Initial implementation of SmilesToMol with RDMol as output.

The internal functions use a certain amount of compatibility routines so it's
far from a perfect implementation. It's also unclear if any checks/modifications
are missing, hopefully further testing will check for that.

Fixed failure in smiTestCatch: Update backend after expandQuery

Fix fileParsersTest1 failure: PropToken handling

Storing and recalling PropTokens wasn't handled correctly. We ensure we store a
PropToken at the parser side, and then RDMol now handles PropTokens who were
stored

Fix pickling of PropTokens

Adjust pickling to ensure that PropTokens are converted to strings before pickling

Fixed MaeWriter code for Properties and PropTokens

Previously free'd query was causing a segfault

This resets the bond query to avoid any use-after-free query invocations

Fixing testSubstructMatch failure by removing numAtomRings check

Some notes, from a debug program I wrote to help fix this:

```
Creating mol from: c12ccc(CCCCCCCc5ccc(C2)cc5)cc1
Creating query from: c1cc2ccc1CCCCCCCc1ccc(cc1)C2

Ring info for mol:
  numRings: 5
  Ring atoms: [1,2,3,18,19,0,] [12,13,14,16,17,11,] [4,5,6,7,8,9,10,11,12,13,14,15,0,1,2,3,] [4,5,6,7,8,9,10,11,17,16,14,15,0,1,2,3,] [18,19,0,15,14,13,12,11,10,9,8,7,6,5,4,3,]

Ring info for query:
  numRings: 6
  Ring atoms: [0,5,4,3,2,1,] [14,15,16,17,18,13,] [6,7,8,9,10,11,12,13,14,15,16,19,2,3,4,5,] [6,7,8,9,10,11,12,13,18,17,16,19,2,3,4,5,] [19,2,1,0,5,6,7,8,9,10,11,12,13,14,15,16,] [17,18,13,12,11,10,9,8,7,6,5,0,1,2,19,16,]
Mol canonical SMILES:   c1cc2ccc1CCCCCCCc1ccc(cc1)C2
Query canonical SMILES: c1cc2ccc1CCCCCCCc1ccc(cc1)C2

Attempting SubstructMatch(*mol, *query)...
Result: FAILED  <-- master branch says is SUCCESS

Attempting SubstructMatch(*query, *mol)...
Result: SUCCESS
Match size: 20
```

In the fixed minimal_rdmol branch, I had to comment out an if checking the number of atom rings, which diverges.

```
if (res) {
    // if (hasOwningMol() && what->hasOwningMol() &&
        // this->getOwningMol().getRingInfo()->isInitialized() &&
        // what->getOwningMol().getRingInfo()->isInitialized() &&
        // this->getOwningMol().getRingInfo()->numAtomRings(d_index) >
            // what->getOwningMol().getRingInfo()->numAtomRings(what->d_index)) {
      // res = false;
  // } else if (!this->getAtomicNum()) {
  if (!this->getAtomicNum()) {
...
```

The master branch doesn't have this atomRing check:

```
if (res) {
  if (!this->getAtomicNum()) {
```

Removed unused code that shouldn't be in public interface

Also: It shouldn't need to exist

Modified existing property compatibility testing to use new interface

Templated over atom & bond to allow property testing using existing function.

Fixed testChemTransforms by fixing an iterator invalidation

The replaceSubstruct tried to replace the same bond twice due to iterator
invalidation. Now we collect indices first and iterator over those instead.

Fix a regression in graphMol tests

Added updatePropertyCache to 'constructForceField' to avoid error

Error: what():  getImplicitValence() called without preceding call to calcImplicitValence()

Similar to a previous bug, need to calculate implicitvalence before using it.

Fix SVG output in case of 0 atomic number.

Adjusted code to better match master reference, despite the slightly confusing
way master is written.

Fixed ordering issue in non-bison smarts parser

Fixed SynthonSpaceSearch: The ringInfo compat needed an update

ringInfo compat interface needs to be re-called when using the compatibility
interface to ensure that the data is properly synced

Fixed testRGroupDecomp: need to add props after atom has owning mol

Fix error in testSLNParse: Remove check preventing multi-setOwningMol

setOwningMol for bonds was prevented from happening more than once. This only
sets a pointer, so I don't know why this would be prevented, so I removed the
check. Obviously one could have issues downstream with indexing and such, but
that is a problem regardless of how many times it is set.

Fixed molStandardizeCatchTest: Test used getDict API which no longer exists

Using getProp instead

Fixed testAbbreviations: Iterator invalidation causing problems

Moved the bond additions after the loop to avoid invalidating the iterator

Fixed pyChemReactions: Re-implemented GetPropsAsDict() avoidng "GetDict()"

New backend doesn't have GetDict(), so we had to replace this using
getPropList() and a sequence of 'try-catch' to get the correct type. This would
be better if we could determine the type of the property before throwing an
exception, but getting the templated type correct for the variety of objects
that use GetPropsAsDict was too complicated so I opted for the simpler approach
using try-catch.

Fixed pyDeprotect: Move string property conversion down, to avoid conversion

It was converting slightly wrong...

Fix a regression in when to autoconvert prop to string

Fixed pyTestPropertyLists: Try Property for uint before int

Avoids an overflow when the property is at uint_max

Fixed pythonProjectTests: Needed to updatePropertyCache after pickling

But also have to wrap that in a try-catch to avoid other errors...

Fixing part of pyGraphMolWrap: better python property overflow handling

Slightly more involved handling of property to python conversion. This handles
overflow scenarios more correctly... the try-catch approach has some faults but
is the best I can come up with at the moment.

Also remove __computedProps check in test, which is deprecated.

Fixing pyGraphMolWrap: large fix to stereo groups compat interface

Added a sync between stereo groups compat interface and the native backend,
because python often uses the compat interface. This required a few non-trivial
changes to pipe through an owning mol to stereo groups and adding a sync
variable to stereo groups in RDMol.

Also fixed another bug with RingInfo

Added handling for inner being a nullptr when calling makeNewNonCompatQuery(). Required for QueryAtom::setQuery(nullptr) and QueryBond::setQuery(nullptr), where the PRECONDITION additionally needs to start with `what == nullptr ||`. This fixes a segfault in molInterchangeCatchTest

Small regression fix: update stereoGroups compat when 0 size